{% set name = "seareport-data" %}
{% set version = "0.2.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seareport_data-{{ version }}.tar.gz
  sha256: 1e2c416ca707928bf5f43375dd61e6608f38edf3ffb01b7c67385a348e6be3e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - dask-core
    - geopandas
    - httpx
    - platformdirs
    - stamina
    - tqdm
    - xarray
    - python-xxhash

test:
  imports:
    - seareport_data
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/seareport/seareport_data
  summary: 'Data retrieval for seareport'
  license: EUPL-1.2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brey
    - pmav99
